name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test one
      id: test-one
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test one
        setup-command: cd pizza*/src ; javac pizza/*.java ; javac pizza/*/*.java
        command: cd pizza*/src ; java pizza/PizzaMain
        input: |
          1
          1
          1
          1
          1
        expected-output: "/.*crust.*/is"
        comparison-method: regex
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-ONE_RESULTS: "${{steps.test-one.outputs.result}}"
      with:
        runners: test-one
